export type Activity = {
    id: number,
    time?: string,
    duration?: number,
    image?: string,
    title: string,
    description?: string,
    location?: string,
    type?: number,
    link?: string,
    photos?: string[],
    price?: number,
    expanded?: boolean,
    showActivity?:boolean,
}