import { countries } from "@/lib/constants/countries"

/** Matches labels in the Explore advanced filter dialog. */
export type ContinentName =
  | "Asia"
  | "Europe"
  | "North America"
  | "South America"
  | "Africa"
  | "Oceania"
  | "Antarctica"

/** ISO 3166-1 alpha-2 → continent (UN M49-ish groupings). */
const CONTINENT_BY_CODE: Record<string, ContinentName> = {
  AF: "Asia",
  AX: "Europe",
  AL: "Europe",
  DZ: "Africa",
  AS: "Oceania",
  AD: "Europe",
  AO: "Africa",
  AI: "North America",
  AQ: "Antarctica",
  AG: "North America",
  AR: "South America",
  AM: "Asia",
  AW: "North America",
  AU: "Oceania",
  AT: "Europe",
  AZ: "Asia",
  BS: "North America",
  BH: "Asia",
  BD: "Asia",
  BB: "North America",
  BY: "Europe",
  BE: "Europe",
  BZ: "North America",
  BJ: "Africa",
  BM: "North America",
  BT: "Asia",
  BO: "South America",
  BA: "Europe",
  BW: "Africa",
  BV: "Antarctica",
  BR: "South America",
  IO: "Asia",
  BN: "Asia",
  BG: "Europe",
  BF: "Africa",
  BI: "Africa",
  KH: "Asia",
  CM: "Africa",
  CA: "North America",
  CV: "Africa",
  KY: "North America",
  CF: "Africa",
  TD: "Africa",
  CL: "South America",
  CN: "Asia",
  CX: "Asia",
  CC: "Asia",
  CO: "South America",
  KM: "Africa",
  CG: "Africa",
  CD: "Africa",
  CK: "Oceania",
  CR: "North America",
  CI: "Africa",
  HR: "Europe",
  CU: "North America",
  CY: "Asia",
  CZ: "Europe",
  DK: "Europe",
  DJ: "Africa",
  DM: "North America",
  DO: "North America",
  EC: "South America",
  EG: "Africa",
  SV: "North America",
  GQ: "Africa",
  ER: "Africa",
  EE: "Europe",
  ET: "Africa",
  FK: "South America",
  FO: "Europe",
  FJ: "Oceania",
  FI: "Europe",
  FR: "Europe",
  GF: "South America",
  PF: "Oceania",
  TF: "Antarctica",
  GA: "Africa",
  GM: "Africa",
  GE: "Asia",
  DE: "Europe",
  GH: "Africa",
  GI: "Europe",
  GR: "Europe",
  GL: "North America",
  GD: "North America",
  GP: "North America",
  GU: "Oceania",
  GT: "North America",
  GG: "Europe",
  GN: "Africa",
  GW: "Africa",
  GY: "South America",
  HT: "North America",
  HM: "Antarctica",
  VA: "Europe",
  HN: "North America",
  HK: "Asia",
  HU: "Europe",
  IS: "Europe",
  IN: "Asia",
  ID: "Asia",
  IR: "Asia",
  IQ: "Asia",
  IE: "Europe",
  IM: "Europe",
  IL: "Asia",
  IT: "Europe",
  JM: "North America",
  JP: "Asia",
  JE: "Europe",
  JO: "Asia",
  KZ: "Asia",
  KE: "Africa",
  KI: "Oceania",
  KP: "Asia",
  KR: "Asia",
  KW: "Asia",
  KG: "Asia",
  LA: "Asia",
  LV: "Europe",
  LB: "Asia",
  LS: "Africa",
  LR: "Africa",
  LY: "Africa",
  LI: "Europe",
  LT: "Europe",
  LU: "Europe",
  MO: "Asia",
  MK: "Europe",
  MG: "Africa",
  MW: "Africa",
  MY: "Asia",
  MV: "Asia",
  ML: "Africa",
  MT: "Europe",
  MH: "Oceania",
  MQ: "North America",
  MR: "Africa",
  MU: "Africa",
  YT: "Africa",
  MX: "North America",
  FM: "Oceania",
  MD: "Europe",
  MC: "Europe",
  MN: "Asia",
  ME: "Europe",
  MS: "North America",
  MA: "Africa",
  MZ: "Africa",
  MM: "Asia",
  NA: "Africa",
  NR: "Oceania",
  NP: "Asia",
  NL: "Europe",
  AN: "North America",
  NC: "Oceania",
  NZ: "Oceania",
  NI: "North America",
  NE: "Africa",
  NG: "Africa",
  NU: "Oceania",
  NF: "Oceania",
  MP: "Oceania",
  NO: "Europe",
  OM: "Asia",
  PK: "Asia",
  PW: "Oceania",
  PS: "Asia",
  PA: "North America",
  PG: "Oceania",
  PY: "South America",
  PE: "South America",
  PH: "Asia",
  PN: "Oceania",
  PL: "Europe",
  PT: "Europe",
  PR: "North America",
  QA: "Asia",
  RE: "Africa",
  RO: "Europe",
  RU: "Europe",
  RW: "Africa",
  SH: "Africa",
  KN: "North America",
  LC: "North America",
  PM: "North America",
  VC: "North America",
  WS: "Oceania",
  SM: "Europe",
  ST: "Africa",
  SA: "Asia",
  SN: "Africa",
  RS: "Europe",
  SC: "Africa",
  SL: "Africa",
  SG: "Asia",
  SK: "Europe",
  SI: "Europe",
  SB: "Oceania",
  SO: "Africa",
  ZA: "Africa",
  GS: "Antarctica",
  ES: "Europe",
  LK: "Asia",
  SD: "Africa",
  SR: "South America",
  SJ: "Europe",
  SZ: "Africa",
  SE: "Europe",
  CH: "Europe",
  SY: "Asia",
  TW: "Asia",
  TJ: "Asia",
  TZ: "Africa",
  TH: "Asia",
  TL: "Asia",
  TG: "Africa",
  TK: "Oceania",
  TO: "Oceania",
  TT: "North America",
  TN: "Africa",
  TR: "Asia",
  TM: "Asia",
  TC: "North America",
  TV: "Oceania",
  UG: "Africa",
  UA: "Europe",
  AE: "Asia",
  GB: "Europe",
  US: "North America",
  UM: "Oceania",
  UY: "South America",
  UZ: "Asia",
  VU: "Oceania",
  VE: "South America",
  VN: "Asia",
  VG: "North America",
  VI: "North America",
  WF: "Oceania",
  EH: "Africa",
  YE: "Asia",
  ZM: "Africa",
  ZW: "Africa",
}

const CONTINENT_BY_COUNTRY_NAME = new Map<string, ContinentName>()
for (const country of countries) {
  const continent = CONTINENT_BY_CODE[country.code.toUpperCase()]
  if (continent) {
    CONTINENT_BY_COUNTRY_NAME.set(country.name.toLowerCase(), continent)
  }
}

/** Extra display aliases that may appear on itinerary days. */
const COUNTRY_ALIASES: Record<string, string> = {
  usa: "united states",
  "united states of america": "united states",
  uk: "united kingdom",
  "great britain": "united kingdom",
  vietnam: "viet nam",
  russia: "russian federation",
  "south korea": "korea, republic of",
  "north korea": "korea, democratic people\"s republic of",
  taiwan: "taiwan, province of china",
  syria: "syrian arab republic",
  laos: "lao people\"s democratic republic",
  moldova: "moldova, republic of",
  tanzania: "tanzania, united republic of",
  iran: "iran, islamic republic of",
  vatican: "holy see (vatican city state)",
  macedonia: "macedonia, the former yugoslav republic of",
  swaziland: "swaziland",
  eswatini: "swaziland",
  czechia: "czech republic",
  "ivory coast": "cote d\"ivoire",
  "côte d'ivoire": "cote d\"ivoire",
}

function normalizeCountryName(name: string): string {
  const key = name.trim().toLowerCase()
  return COUNTRY_ALIASES[key] || key
}

export function getContinentForCountry(countryName: string): ContinentName | null {
  return CONTINENT_BY_COUNTRY_NAME.get(normalizeCountryName(countryName)) || null
}

/** Country names (as in `countries.ts` / day.country) for the selected continents. */
export function getCountryNamesForContinents(continents: string[]): string[] {
  if (!continents.length) return []
  const wanted = new Set(
    continents.map((c) => c.trim().toLowerCase()).filter(Boolean)
  )
  return countries
    .filter((c) => {
      const continent = CONTINENT_BY_CODE[c.code.toUpperCase()]
      return continent ? wanted.has(continent.toLowerCase()) : false
    })
    .map((c) => c.name)
}
